---
on:
  push:
    branches:
      - "master"
  pull_request:
    types:
      - opened
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    environment: development
    steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v2.0.0
          with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Checkout
          uses: actions/checkout@v2
        - name: Test
          run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
